"""add prizes table

Revision ID: 001a54102bb0
Revises: 347bb92a4846
Create Date: 2023-04-02 23:57:18.777143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001a54102bb0'
down_revision = '347bb92a4846'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prizes')
    # ### end Alembic commands ###
