"""add init tables

Revision ID: 347bb92a4846
Revises: 
Create Date: 2023-04-02 16:17:33.532337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347bb92a4846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('players',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('second_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('answer', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_whole_word', sa.Boolean(), nullable=True),
    sa.Column('pinned_message_id', sa.Integer(), nullable=True),
    sa.Column('played_letters', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('move', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['players.tg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.tg_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_table('games')
    op.drop_table('questions')
    op.drop_table('players')
    op.drop_table('admins')
    # ### end Alembic commands ###
