"""add initial tables

Revision ID: 484edeeeb087
Revises: 
Create Date: 2023-03-19 14:31:47.954930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484edeeeb087'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
