"""change dependencies between tables

Revision ID: 5bb9ed3c46e3
Revises: 7ec9fc0dfd2c
Create Date: 2023-03-19 19:53:50.994580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb9ed3c46e3'
down_revision = '7ec9fc0dfd2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_score_fkey', 'players', type_='foreignkey')
    op.drop_column('players', 'score')
    op.add_column('score', sa.Column('player_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'score', 'players', ['player_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'player_id')
    op.add_column('players', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('players_score_fkey', 'players', 'score', ['score'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
