"""add foreign keys

Revision ID: 7ec9fc0dfd2c
Revises: 484edeeeb087
Create Date: 2023-03-19 14:42:42.521918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec9fc0dfd2c'
down_revision = '484edeeeb087'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('score', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'players', 'score', ['score'], ['id'], ondelete='CASCADE')
    op.add_column('score', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'score', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'game_id')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'score')
    # ### end Alembic commands ###
